# Generated by Django 4.0.5 on 2022-06-13 14:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, validators=[django.core.validators.MinValueValidator(3)])),
                ('description', models.CharField(max_length=200, validators=[django.core.validators.MinValueValidator(10)])),
                ('picture_file', models.FileField(blank=True, null=True, upload_to='pictures/')),
                ('last_update_timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, validators=[django.core.validators.MinValueValidator(10)])),
                ('step_number', models.IntegerField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('KG', 'KG'), ('g', 'g'), ('L', 'L'), ('ml', 'ml'), ('units', 'units')], max_length=5)),
                ('amount', models.FloatField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
    ]
