# Generated by Django 4.0.5 on 2022-06-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredient_recipe_alter_recipe_picture_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='step_number',
            new_name='index',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='picture_file',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
    ]
