# Generated by Django 4.0.5 on 2022-07-01 01:38

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_rename_description_step_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Dinner', 'Dinner'), ('Breakfast', 'Breakfast'), ('Salad', 'Salad'), ('Dessert', 'Dessert')], max_length=248, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='step',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
