# Generated by Django 4.0.5 on 2022-07-01 01:44

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_type_alter_step_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='type',
        ),
        migrations.AddField(
            model_name='recipe',
            name='types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Dinner', 'Dinner'), ('Breakfast', 'Breakfast'), ('Salad', 'Salad'), ('Dessert', 'Dessert')], max_length=30, null=True),
        ),
    ]
